// topology_engine/tests/fixture_io.hpp
//
// Golden-fixture serialisation for PowerMatrix.
//
// FORMAT DECISION: pipe-delimited text, not JSON.
//   - Zero dependencies. No FetchContent, no network, no vendored headers.
//   - One node per line, sorted by id, so `git diff` on a fixture names exactly
//     which node changed. A JSON diff would reflow and hide that.
//   - Trivially parseable with the standard library alone.
//
// FLOAT DECISION: values are written at fixed precision for readable diffs, but
// compared NUMERICALLY with an epsilon. Comparing formatted strings is the
// classic golden-test trap — a value landing on a rounding boundary flips its
// last digit between compilers and the suite goes flaky for no real reason.

#ifndef FIXTURE_IO_HPP
#define FIXTURE_IO_HPP

#include "../core/include/PowerMatrix.hpp"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>
#include <map>

namespace Fixture {

// Tolerance for float comparison. The engine works in volts, amps and kW —
// values in the 1..10000 range — so 1e-3 is far tighter than any physically
// meaningful difference, while absorbing platform FP noise.
constexpr double EPSILON = 1e-3;

// ── Serialisation ─────────────────────────────────────────────────────────

inline std::string num(double v) {
    std::ostringstream os;
    os << std::fixed << std::setprecision(3) << v;
    return os.str();
}

// Writes the complete observable state of the engine: globals first (prefixed
// '!'), then every node sorted by id.
inline std::string serialise(const Topology::PowerMatrix& pm,
                             const std::string& scenario_name) {
    std::ostringstream os;
    os << "# DCIMe golden fixture - scenario: " << scenario_name << "\n";
    os << "# generated by golden_gen; do not hand-edit\n";

    os << "!grid_active="    << (pm.getGridActive()      ? 1 : 0) << "\n";
    os << "!fire_alarm="     << (pm.getFireAlarmActive() ? 1 : 0) << "\n";
    os << "!cooling_active=" << (pm.getCoolingActive()   ? 1 : 0) << "\n";
    os << "!dg_auto="        << (pm.getDgAuto()          ? 1 : 0) << "\n";
    os << "!fuel_liters="    << num(pm.getFuelLiters())  << "\n";
    os << "!ambient_temp="   << num(pm.getAmbientTemp()) << "\n";
    os << "!battery_soc="    << num(pm.getBatterySoc())  << "\n";
    os << "!gen_status="     << pm.getGenStatus()        << "\n";
    os << "!dg_pair_status=" << pm.getDgPairStatus()     << "\n";
    os << "!active_dg_pair=" << pm.getActiveDgPair()     << "\n";
    os << "!pair_run_secs="  << num(pm.getPairRunSeconds()) << "\n";
    for (int i = 0; i < 4; ++i) {
        os << "!dg_run_hours_" << i << "=" << num(pm.getDgRunHours(i)) << "\n";
    }

    std::vector<Topology::Node> nodes = pm.getNodes();
    std::sort(nodes.begin(), nodes.end(),
              [](const Topology::Node& a, const Topology::Node& b) {
                  return a.id < b.id;
              });

    for (const auto& n : nodes) {
        os << n.id            << '|'
           << n.status        << '|'
           << (n.is_active  ? 1 : 0) << '|'
           << (n.is_faulted ? 1 : 0) << '|'
           << num(n.voltage)         << '|'
           << num(n.current)         << '|'
           << num(n.kw_load)         << '|'
           << num(n.load_pct)        << '|'
           << num(n.runtime_minutes) << "\n";
    }
    return os.str();
}

// ── Parsing ───────────────────────────────────────────────────────────────

struct NodeState {
    std::string status;
    bool   is_active  = false;
    bool   is_faulted = false;
    double voltage = 0, current = 0, kw_load = 0, load_pct = 0, runtime = 0;
};

struct Snapshot {
    std::map<std::string, std::string>  globals;  // raw text, compared below
    std::map<std::string, NodeState>    nodes;
};

inline std::vector<std::string> split(const std::string& s, char delim) {
    std::vector<std::string> out;
    std::string part;
    std::istringstream is(s);
    while (std::getline(is, part, delim)) out.push_back(part);
    return out;
}

inline Snapshot parse(const std::string& text) {
    Snapshot snap;
    std::istringstream is(text);
    std::string line;
    while (std::getline(is, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();   // CRLF safety
        if (line.empty() || line[0] == '#') continue;

        if (line[0] == '!') {
            auto eq = line.find('=');
            if (eq == std::string::npos) continue;
            snap.globals[line.substr(1, eq - 1)] = line.substr(eq + 1);
            continue;
        }

        auto f = split(line, '|');
        if (f.size() < 9) continue;
        NodeState ns;
        ns.status     = f[1];
        ns.is_active  = (f[2] == "1");
        ns.is_faulted = (f[3] == "1");
        ns.voltage    = std::stod(f[4]);
        ns.current    = std::stod(f[5]);
        ns.kw_load    = std::stod(f[6]);
        ns.load_pct   = std::stod(f[7]);
        ns.runtime    = std::stod(f[8]);
        snap.nodes[f[0]] = ns;
    }
    return snap;
}

inline bool read_file(const std::string& path, std::string& out) {
    std::ifstream in(path, std::ios::binary);
    if (!in) return false;
    std::ostringstream os;
    os << in.rdbuf();
    out = os.str();
    return true;
}

inline bool write_file(const std::string& path, const std::string& content) {
    std::ofstream out(path, std::ios::binary);
    if (!out) return false;
    out << content;
    return true;
}

// ── Comparison ────────────────────────────────────────────────────────────

inline bool near(double a, double b) { return std::fabs(a - b) <= EPSILON; }

// Compares two snapshots, appending human-readable differences to `diffs`.
// Returns true when they match.
inline bool compare(const Snapshot& expected,
                    const Snapshot& actual,
                    std::vector<std::string>& diffs) {

    for (const auto& kv : expected.globals) {
        auto it = actual.globals.find(kv.first);
        if (it == actual.globals.end()) {
            diffs.push_back("  global '" + kv.first + "' missing from actual");
            continue;
        }
        // Numeric where possible, textual otherwise (gen_status et al).
        try {
            size_t ea = 0, eb = 0;
            double x = std::stod(kv.second, &ea);
            double y = std::stod(it->second, &eb);
            if (ea == kv.second.size() && eb == it->second.size()) {
                if (!near(x, y)) {
                    diffs.push_back("  global '" + kv.first + "': expected "
                                    + kv.second + ", got " + it->second);
                }
                continue;
            }
        } catch (...) { /* fall through to string compare */ }

        if (kv.second != it->second) {
            diffs.push_back("  global '" + kv.first + "': expected '"
                            + kv.second + "', got '" + it->second + "'");
        }
    }

    for (const auto& kv : expected.nodes) {
        auto it = actual.nodes.find(kv.first);
        if (it == actual.nodes.end()) {
            diffs.push_back("  node '" + kv.first + "' missing from actual");
            continue;
        }
        const NodeState& e = kv.second;
        const NodeState& a = it->second;
        const std::string& id = kv.first;

        if (e.status != a.status)
            diffs.push_back("  " + id + ".status: expected '" + e.status
                            + "', got '" + a.status + "'");
        if (e.is_active != a.is_active)
            diffs.push_back("  " + id + ".is_active differs");
        if (e.is_faulted != a.is_faulted)
            diffs.push_back("  " + id + ".is_faulted differs");
        if (!near(e.voltage, a.voltage))
            diffs.push_back("  " + id + ".voltage: expected " + num(e.voltage)
                            + ", got " + num(a.voltage));
        if (!near(e.current, a.current))
            diffs.push_back("  " + id + ".current: expected " + num(e.current)
                            + ", got " + num(a.current));
        if (!near(e.kw_load, a.kw_load))
            diffs.push_back("  " + id + ".kw_load: expected " + num(e.kw_load)
                            + ", got " + num(a.kw_load));
        if (!near(e.load_pct, a.load_pct))
            diffs.push_back("  " + id + ".load_pct: expected " + num(e.load_pct)
                            + ", got " + num(a.load_pct));
        if (!near(e.runtime, a.runtime))
            diffs.push_back("  " + id + ".runtime_minutes: expected "
                            + num(e.runtime) + ", got " + num(a.runtime));
    }

    for (const auto& kv : actual.nodes) {
        if (expected.nodes.find(kv.first) == expected.nodes.end())
            diffs.push_back("  node '" + kv.first + "' appeared in actual but "
                            "is not in the fixture");
    }

    return diffs.empty();
}

} // namespace Fixture

#endif // FIXTURE_IO_HPP
