-- ═══════════════════════════════════════════════════════════════════════════
-- 20260814_seed_topology_layout.sql
-- GENERATED by scripts/extract_topology_layout.py — do not hand-edit.
--
-- Geometry lifted verbatim from
-- public/topology_engine/renderer/index.html so the database-driven render
-- is pixel-identical to the hand-drawn original. Any visual difference after
-- the Stage 3 cutover is a bug in the renderer, not a change of design.
--
-- 50 node positions, 52 routed cables.
-- Scoped to the SANDBOX site; production sites are untouched.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

CREATE TEMP TABLE _layout(equipment_id text PRIMARY KEY, x double precision,
                         y double precision, shape text) ON COMMIT DROP;

INSERT INTO _layout(equipment_id, x, y, shape) VALUES
  ('node-ac-server-db', 1100.0, 4800.0, 'server'),
  ('node-ac-server-db-b', 1700.0, 4800.0, 'server'),
  ('node-ac-ups-db-a', 1000.0, 1750.0, 'db'),
  ('node-ac-ups-db-b', 3100.0, 750.0, 'db'),
  ('node-aircon-db-a', 1000.0, 2250.0, 'db'),
  ('node-aircon-db-b', 3100.0, 1250.0, 'db'),
  ('node-dc-rect-db-a', 1000.0, 2000.0, 'db'),
  ('node-dc-rect-db-b', 3100.0, 1000.0, 'db'),
  ('node-dc-server-db', 1900.0, 4000.0, 'server'),
  ('node-dc-server-db-b', 2500.0, 4000.0, 'server'),
  ('dg_1', 300.0, 300.0, 'generator'),
  ('dg_2', 650.0, 300.0, 'generator'),
  ('dg_3', 1000.0, 300.0, 'generator'),
  ('dg_4', 1350.0, 300.0, 'generator'),
  ('node-dg-bus', 1000.0, 150.0, 'bus'),
  ('dg_hq', 1700.0, 300.0, 'generator'),
  ('pac_data_em1', 3450.0, 3000.0, 'aircon'),
  ('pac_data_em2', 4050.0, 3000.0, 'aircon'),
  ('pac_server_dragor', 1500.0, 4400.0, 'aircon'),
  ('fm200_panel', 1100.0, 900.0, 'fss'),
  ('grid_main', 300.0, 900.0, 'transformer'),
  ('pac_it1_em1', 2450.0, 1600.0, 'aircon'),
  ('pac_it1_em2', 2750.0, 2000.0, 'aircon'),
  ('pac_it2_em1', 3450.0, 1600.0, 'aircon'),
  ('pac_it2_em2', 3750.0, 2000.0, 'aircon'),
  ('node-main-main-db', 700.0, 900.0, 'db'),
  ('node-maindb-1', 2700.0, 1000.0, 'db'),
  ('node-maindb-2', 600.0, 2000.0, 'db'),
  ('pac_pr1_em1', 3900.0, 600.0, 'aircon'),
  ('pac_pr1_em2', 3900.0, 900.0, 'aircon'),
  ('node-pr1-ac-3', 3900.0, 1200.0, 'aircon'),
  ('pac_pr2_em1', 1800.0, 1600.0, 'aircon'),
  ('pac_pr2_em2', 1800.0, 2200.0, 'aircon'),
  ('rectifier_1', 3500.0, 1000.0, 'rectifier'),
  ('rectifier_2', 1400.0, 2000.0, 'rectifier'),
  ('pac_server_em1', 300.0, 3100.0, 'aircon'),
  ('pac_server_em2', 700.0, 3100.0, 'aircon'),
  ('pac_server_em3', 1100.0, 3100.0, 'aircon'),
  ('pac_server_em4', 1500.0, 3100.0, 'aircon'),
  ('pac_server_em5', 1900.0, 3100.0, 'aircon'),
  ('pac_server_em6', 2300.0, 3100.0, 'aircon'),
  ('pac_server_em7', 2700.0, 3100.0, 'aircon'),
  ('node-tco-1', 200.0, 2000.0, 'tco'),
  ('node-tco-2', 2300.0, 1000.0, 'tco'),
  ('ups_1', 3500.0, 750.0, 'ups'),
  ('ups_2', 1400.0, 1750.0, 'ups'),
  ('pac_server_vt1', 300.0, 3600.0, 'aircon'),
  ('pac_server_vt2', 300.0, 4000.0, 'aircon'),
  ('pac_server_vt3', 300.0, 4400.0, 'aircon'),
  ('pac_server_vt4', 300.0, 4800.0, 'aircon'),
  ('pac_server_vt5', 300.0, 5200.0, 'aircon'),
  ('pac_data_vt6', 3750.0, 3700.0, 'aircon');

UPDATE public.equipment_registry e
   SET layout_x = l.x, layout_y = l.y, render_shape = l.shape
  FROM _layout l
 WHERE e.equipment_id = l.equipment_id
   AND e.site_uuid = (SELECT id FROM public.sites WHERE site_code = 'SANDBOX');

-- The busbar is drawn as a line rather than a cube, so its geometry lives
-- on the node itself.
UPDATE public.equipment_registry
   SET render_path_d = 'M 300 150 L 1700 150'
 WHERE equipment_id = 'node-dg-bus'
   AND site_uuid = (SELECT id FROM public.sites WHERE site_code = 'SANDBOX');

-- ── Room floor plates ─────────────────────────────────────────────────────
CREATE TEMP TABLE _plates(room_name text PRIMARY KEY, label text,
  x double precision, y double precision, w double precision, h double precision,
  lx double precision, ly double precision, fs integer, tint text) ON COMMIT DROP;

INSERT INTO _plates(room_name, label, x, y, w, h, lx, ly, fs, tint) VALUES
  ('Data Room', 'THE DATA ROOM', 3200.0, 2800.0, 1100.0, 1200.0, 3230.0, 2850.0, 24, 'rgba(255, 255, 255, 0.01)'),
  ('Genset Yard', 'EXTERIOR YARD', 100.0, 100.0, 1900.0, 1000.0, 130.0, 160.0, 28, 'rgba(255, 255, 255, 0.01)'),
  ('IT Room 1', 'IT ROOM 1', 2200.0, 1400.0, 900.0, 800.0, 2220.0, 1450.0, 20, 'rgba(255, 255, 255, 0.01)'),
  ('IT Room 2', 'IT ROOM 2', 3200.0, 1400.0, 1000.0, 800.0, 3220.0, 1450.0, 20, 'rgba(255, 255, 255, 0.01)'),
  ('Power Room 1', 'POWER ROOM 1', 2200.0, 100.0, 1900.0, 1250.0, 2230.0, 160.0, 28, 'rgba(16, 185, 129, 0.01)'),
  ('Power Room 2', 'POWER ROOM 2', 100.0, 1400.0, 1900.0, 1100.0, 130.0, 1460.0, 28, 'rgba(0, 240, 255, 0.01)'),
  ('Server Room', 'THE SERVER ROOM', 100.0, 2800.0, 2900.0, 3000.0, 150.0, 2870.0, 36, 'rgba(255, 255, 255, 0.015)');

UPDATE public.rooms rm
   SET layout_x = p.x, layout_y = p.y, layout_w = p.w, layout_h = p.h,
       layout_label = p.label, label_x = p.lx, label_y = p.ly,
       label_size = p.fs, layout_tint = p.tint
  FROM _plates p
 WHERE rm.room_name = p.room_name
   AND rm.site_id = (SELECT id FROM public.sites WHERE site_code = 'SANDBOX');

-- ── Room assignment follows the drawing ───────────────────────────────────
-- Where a node is DRAWN is surveyed fact; which room it was tagged with is a
-- guess made when the seed was written. So room_id is derived from plate
-- containment, not the other way round. This corrected six nodes on first
-- run, all of them mismatches inherited from the V1 seed.
UPDATE public.equipment_registry e
   SET room_id = rm.id
  FROM public.rooms rm
 WHERE rm.site_id = e.site_uuid
   AND rm.layout_x IS NOT NULL
   AND e.layout_x IS NOT NULL
   AND e.layout_x BETWEEN rm.layout_x AND rm.layout_x + rm.layout_w
   AND e.layout_y BETWEEN rm.layout_y AND rm.layout_y + rm.layout_h
   AND e.site_uuid = (SELECT id FROM public.sites WHERE site_code = 'SANDBOX')
   AND e.room_id IS DISTINCT FROM rm.id;

CREATE TEMP TABLE _paths(render_path_id text PRIMARY KEY, d text) ON COMMIT DROP;

INSERT INTO _paths(render_path_id, d) VALUES
  ('acdba-to-ac1', 'M 1000 2250 L 1000 2550 L 1000 2950 L 300 2950 L 300 3100'),
  ('acdba-to-ac2', 'M 1000 2950 L 700 2950 L 700 3100'),
  ('acdba-to-ac6', 'M 1000 2950 L 2300 2950 L 2300 3100'),
  ('acdba-to-ac7', 'M 1000 2950 L 2700 2950 L 2700 3100'),
  ('acdbb-to-ac3', 'M 1900 2950 L 1100 2950 L 1100 3100'),
  ('acdbb-to-ac4', 'M 1900 2950 L 1500 2950 L 1500 3100'),
  ('acdbb-to-ac5', 'M 3100 1250 L 3100 2950 L 1900 2950 L 1900 3100'),
  ('acdbb-to-drac1', 'M 3100 1250 L 3300 1250 L 3300 2900 L 3450 2900 L 3450 3000'),
  ('acdbb-to-drac2', 'M 3450 2900 L 4050 2900 L 4050 3000'),
  ('acdbb-to-it1ac1', 'M 3100 1250 L 2450 1250 L 2450 1600'),
  ('acdbb-to-it1ac2', 'M 2450 1250 L 2750 1250 L 2750 2000'),
  ('acdbb-to-it2ac1', 'M 3100 1250 L 3450 1250 L 3450 1600'),
  ('acdbb-to-it2ac2', 'M 3450 1250 L 3750 1250 L 3750 2000'),
  ('acdbb-to-pr1ac1', 'M 3100 1250 L 3700 1250 L 3700 600 L 3900 600'),
  ('acdbb-to-pr1ac2', 'M 3700 1250 L 3700 900 L 3900 900'),
  ('acdbb-to-pr1ac3', 'M 3700 1250 L 3900 1200'),
  ('acdbb-to-pr2ac1', 'M 3100 1250 L 2100 1250 L 2100 1600 L 1800 1600'),
  ('acdbb-to-pr2ac2', 'M 2100 1600 L 2100 2200 L 1800 2200'),
  ('acserverdb-to-vertiv1', 'M 1100 4800 L 500 4800 L 500 3600 L 300 3600'),
  ('acserverdb-to-vertiv2', 'M 500 4800 L 500 4000 L 300 4000'),
  ('dcserverdb-to-vertiv3', 'M 1900 4000 L 600 4000 L 600 4400 L 300 4400'),
  ('dcserverdb-to-vertiv4', 'M 600 4000 L 600 4800 L 300 4800'),
  ('dcserverdb-to-vertiv5', 'M 600 4000 L 600 5200 L 300 5200'),
  ('dcserverdb-to-vertiv6', 'M 1900 4000 L 3750 4000 L 3750 3700'),
  ('dg-bus', 'M 300 150 L 1700 150'),
  ('dg-cable-1', 'M 300 300 L 300 150'),
  ('dg-cable-2', 'M 650 300 L 650 150'),
  ('dg-cable-3', 'M 1000 300 L 1000 150'),
  ('dg-cable-4', 'M 1350 300 L 1350 150'),
  ('dg-cable-hq', 'M 1700 300 L 1700 150'),
  ('dg-to-tco1', 'M 300 150 L 150 150 L 150 2000 L 200 2000'),
  ('dg-to-tco2', 'M 1700 150 L 2250 150 L 2250 1000 L 2300 1000'),
  ('grid-to-main', 'M 300 900 L 700 900'),
  ('main-to-tco1', 'M 700 900 L 700 1300 L 200 1300 L 200 2000'),
  ('main-to-tco2', 'M 700 900 L 1200 900 L 1200 1100 L 2300 1100 L 2300 1000'),
  ('maindb1-to-acdbb', 'M 2700 1000 L 2900 1000 L 2900 1250 L 3100 1250'),
  ('maindb1-to-rectdbb', 'M 2700 1000 L 3100 1000'),
  ('maindb1-to-upsdbb', 'M 2700 1000 L 2900 1000 L 2900 750 L 3100 750'),
  ('maindb2-to-acdba', 'M 600 2000 L 800 2000 L 800 2250 L 1000 2250'),
  ('maindb2-to-rectdba', 'M 600 2000 L 1000 2000'),
  ('maindb2-to-upsdba', 'M 600 2000 L 800 2000 L 800 1750 L 1000 1750'),
  ('rect1-to-dcserverdb', 'M 3500 1000 L 3650 1000 L 3650 2700 L 1900 2700 L 1900 4000'),
  ('rect2-to-dcserverdb', 'M 1400 2000 L 1650 2000 L 1650 2700 L 1900 2700 L 1900 4000'),
  ('rectdba-to-rect2', 'M 1000 2000 L 1400 2000'),
  ('rectdbb-to-rect1', 'M 3100 1000 L 3500 1000'),
  ('tco1-to-maindb2', 'M 200 2000 L 600 2000'),
  ('tco2-to-dragor', 'M 2300 1000 L 2150 1000 L 2150 2600 L 1500 2600 L 1500 4400'),
  ('tco2-to-maindb1', 'M 2300 1000 L 2700 1000'),
  ('ups1-to-acserverdb', 'M 3500 750 L 3600 750 L 3600 2600 L 1100 2600 L 1100 4800'),
  ('ups2-to-acserverdb', 'M 1400 1750 L 1600 1750 L 1600 2650 L 1100 2650 L 1100 4800'),
  ('upsdba-to-ups2', 'M 1000 1750 L 1400 1750'),
  ('upsdbb-to-ups1', 'M 3100 750 L 3500 750');

UPDATE public.equipment_connections c
   SET render_path_d = p.d
  FROM _paths p, public.equipment_registry e
 WHERE c.render_path_id = p.render_path_id
   AND e.equipment_id = c.source_equipment_id
   AND e.site_uuid = (SELECT id FROM public.sites WHERE site_code = 'SANDBOX');

-- ── Report what landed, and what did not ──────────────────────────────────
DO $$
DECLARE v_site uuid; v_pos int; v_shape int; v_d int; v_nodrawn int; v_rooms int; v_out int;
BEGIN
  SELECT id INTO v_site FROM public.sites WHERE site_code = 'SANDBOX';
  SELECT count(*) INTO v_pos   FROM public.equipment_registry
   WHERE site_uuid = v_site AND layout_x IS NOT NULL;
  SELECT count(*) INTO v_shape FROM public.equipment_registry
   WHERE site_uuid = v_site AND render_shape IS NOT NULL;
  SELECT count(*) INTO v_d FROM public.equipment_connections c
    JOIN public.equipment_registry e ON e.equipment_id = c.source_equipment_id
   WHERE e.site_uuid = v_site AND c.render_path_d IS NOT NULL;
  SELECT count(*) INTO v_nodrawn FROM public.equipment_registry
   WHERE site_uuid = v_site AND engine_type IS NOT NULL AND layout_x IS NULL;
  SELECT count(*) INTO v_rooms FROM public.rooms
   WHERE site_id = v_site AND layout_x IS NOT NULL;
  SELECT count(*) INTO v_out FROM public.topology_layout_issues
   WHERE site_uuid = v_site;
  RAISE NOTICE 'layout: % positioned, % shaped, % cables routed, % rooms plated, % outside a room',
    v_pos, v_shape, v_d, v_rooms, v_out;
  IF v_nodrawn > 0 THEN
    RAISE EXCEPTION '% simulated node(s) have no coordinates - they would be invisible', v_nodrawn;
  END IF;
END $$;

COMMIT;
